// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Linear.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Linear_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Linear_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Linear_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Linear_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Linear_2eproto;
namespace IIRF {
class DriveTrainSimple;
class DriveTrainSimpleDefaultTypeInternal;
extern DriveTrainSimpleDefaultTypeInternal _DriveTrainSimple_default_instance_;
}  // namespace IIRF
PROTOBUF_NAMESPACE_OPEN
template<> ::IIRF::DriveTrainSimple* Arena::CreateMaybeMessage<::IIRF::DriveTrainSimple>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace IIRF {

// ===================================================================

class DriveTrainSimple :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:IIRF.DriveTrainSimple) */ {
 public:
  DriveTrainSimple();
  virtual ~DriveTrainSimple();

  DriveTrainSimple(const DriveTrainSimple& from);
  DriveTrainSimple(DriveTrainSimple&& from) noexcept
    : DriveTrainSimple() {
    *this = ::std::move(from);
  }

  inline DriveTrainSimple& operator=(const DriveTrainSimple& from) {
    CopyFrom(from);
    return *this;
  }
  inline DriveTrainSimple& operator=(DriveTrainSimple&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DriveTrainSimple& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DriveTrainSimple* internal_default_instance() {
    return reinterpret_cast<const DriveTrainSimple*>(
               &_DriveTrainSimple_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(DriveTrainSimple* other);
  friend void swap(DriveTrainSimple& a, DriveTrainSimple& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DriveTrainSimple* New() const final {
    return CreateMaybeMessage<DriveTrainSimple>(nullptr);
  }

  DriveTrainSimple* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DriveTrainSimple>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DriveTrainSimple& from);
  void MergeFrom(const DriveTrainSimple& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DriveTrainSimple* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "IIRF.DriveTrainSimple";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Linear_2eproto);
    return ::descriptor_table_Linear_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 linear = 1;
  bool has_linear() const;
  void clear_linear();
  static const int kLinearFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int32 linear() const;
  void set_linear(::PROTOBUF_NAMESPACE_ID::int32 value);

  // required int32 angular = 2;
  bool has_angular() const;
  void clear_angular();
  static const int kAngularFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::int32 angular() const;
  void set_angular(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:IIRF.DriveTrainSimple)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 linear_;
  ::PROTOBUF_NAMESPACE_ID::int32 angular_;
  friend struct ::TableStruct_Linear_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DriveTrainSimple

// required int32 linear = 1;
inline bool DriveTrainSimple::has_linear() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DriveTrainSimple::clear_linear() {
  linear_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 DriveTrainSimple::linear() const {
  // @@protoc_insertion_point(field_get:IIRF.DriveTrainSimple.linear)
  return linear_;
}
inline void DriveTrainSimple::set_linear(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  linear_ = value;
  // @@protoc_insertion_point(field_set:IIRF.DriveTrainSimple.linear)
}

// required int32 angular = 2;
inline bool DriveTrainSimple::has_angular() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DriveTrainSimple::clear_angular() {
  angular_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 DriveTrainSimple::angular() const {
  // @@protoc_insertion_point(field_get:IIRF.DriveTrainSimple.angular)
  return angular_;
}
inline void DriveTrainSimple::set_angular(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  angular_ = value;
  // @@protoc_insertion_point(field_set:IIRF.DriveTrainSimple.angular)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace IIRF

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Linear_2eproto
