RobotName: ""
Author: "" 
Date: ""
Peripherals:
        - Name: ""
          Type: ""
          Motors:
                  - Name: ""
                    Type: ""
                    .......
                  - Name: ""
                    Type: ""
                    .......
        - Name: ""
          ......
