#!/bin/bash

virtualenv -p python3 ../venv
source ../venv/bin/activate
pip install -r requirements.txt
deactivate


echo "Environment is now set up"
echo "Before requiring python, remember to execute the command"
echo ""
echo "$ source ./venv/bin/activate"
echo ""
echo "$ deactivate #to exit"
